### ISSUE TITLE
handle pouchdb change event

### ISSUE THREAD

**Issue by vicentedealencar** [yanick/redux-persist-pouchdb#2]
is this on the roadmap?

so that a remote couchdb may be replicating with your pouchdb, updating the redux state as result

**Comment by yanick** [comment]
> is this on the roadmap?

It is now. :-)

**Comment by yanick** [comment]
It has taken way too long, but I've added a small recipe to the README for this.

**Comment by williamleathers** [comment]
Hey @yanick , many thanks for all your work on this package :)

**Comment by yanick** [comment]
You are very welcome. :-)
